//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bribes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub bribe_address: String,
    #[sea_orm(column_type = "Double")]
    pub reward_amount: f64,
    pub chain_id: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub token_address: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub pair_address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assets::Entity",
        from = "(Column::TokenAddress, Column::TokenAddress, Column::ChainId, Column::ChainId)",
        to = "(super::assets::Column::Address, super::assets::Column::ChainId, super::assets::Column::Address, super::assets::Column::ChainId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Assets,
    #[sea_orm(
        belongs_to = "super::pairs::Entity",
        from = "(Column::PairAddress, Column::PairAddress, Column::ChainId, Column::ChainId)",
        to = "(super::pairs::Column::ChainId, super::pairs::Column::Address, super::pairs::Column::ChainId, super::pairs::Column::Address)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pairs,
}

impl Related<super::assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assets.def()
    }
}

impl Related<super::pairs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pairs.def()
    }
}

impl Related<super::aprs::Entity> for Entity {
    fn to() -> RelationDef {
        super::assets::Relation::Aprs.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::assets::Relation::Bribes.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
