//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "gauges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub address: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub chain_id: i32,
    pub decimals: i32,
    #[sea_orm(column_type = "Double")]
    pub total_supply: f64,
    #[sea_orm(column_type = "Text")]
    pub bribe_address: String,
    #[sea_orm(column_type = "Double")]
    pub reward: f64,
    #[sea_orm(column_type = "Double")]
    pub median_tbv: f64,
    #[sea_orm(column_type = "Double")]
    pub min_tbv: f64,
    #[sea_orm(column_type = "Double")]
    pub max_tbv: f64,
    #[sea_orm(column_type = "Double")]
    pub votes: f64,
    #[sea_orm(column_type = "Double")]
    pub min_apr: f64,
    #[sea_orm(column_type = "Double")]
    pub max_apr: f64,
    #[sea_orm(column_type = "Text")]
    pub pair_address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pairs::Entity",
        from = "(Column::PairAddress, Column::ChainId)",
        to = "(super::pairs::Column::Address, super::pairs::Column::ChainId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pairs,
}

impl Related<super::pairs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pairs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
